### PR TITLE
Adding OIDC login

### PR DESCRIPTION
**Pull request by juliakm**
## Purpose

* Adding the OIDC login method for authentication. 

Related article: https://docs.microsoft.com/en-us/azure/app-service/app-service-sql-asp-github-actions
## Does this introduce a breaking change?

```
[ ] Yes
[ X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone https://github.com/Azure-Samples/dotnetcore-sqldb-ghactions.git
cd dotnetcore-sqldb-ghactions
git checkout main
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by juliakm** [comment]
@vermegi Can you review this when you have a chance?

**Review by vermegi — COMMENTED** [review]
With this change, also review the guidance in the README.md file: 
https://github.com/Azure-Samples/dotnetcore-sqldb-ghactions/blob/846a7427fb283f66c75a890468f57a1c27ec7339/README.md?plain=1#L46

**Comment by juliakm** [comment]
@vermegi Could you take a look at this PR?

**Comment by vermegi** [comment]
Looks good! I'll merge it in.

**Pull request merged**
